cmd /c npm i eslint -g
cmd /c npm i eslint-plugin-react -g
cmd /c npm i eslint-config-airbnb -g
cmd /c npm i babel-eslint -g
cmd /c npm i bower -g
cmd /c npm i gulp -g
cmd /c npm i karma -g
cmd /c npm i nodemon -g
cmd /c npm i node-gyp -g
cmd /c npm i browser-sync -g
cmd /c npm i node-sass -g
cmd /c npm i npm -g
cmd /c npm i pangyp -g
cmd /c npm i phantomjs-prebuilt -g
cmd /c npm i sass-lint -g
cmd /c npm i webpack -g
cmd /c npm i webpack-dev-server -g