const EditorNames = {
  EDIT_WEBSITE_DETAILS: 'EDIT_WEBSITE_DETAILS',
  EDIT_WEBSITE_FOLDER_DETAILS: 'EDIT_WEBSITE_FOLDER_DETAILS',
  EDIT_WEBSITE_PAGE_DETAILS: 'EDIT_WEBSITE_PAGE_DETAILS',
  EDIT_LAYOUT_DETAILS: 'EDIT_LAYOUT_DETAILS',
  Wizards: {
    CONFIGURE_DDL: 'CONFIGURE_DDL'
  }
};

export default EditorNames;
