const EditorNames = {
  EDIT_WEBSITE_DETAILS: 'EDIT_WEBSITE_DETAILS',
  EDIT_WEBSITE_FOLDER_DETAILS: 'EDIT_WEBSITE_FOLDER_DETAILS',
  EDIT_WEBSITE_PAGE_DETAILS: 'EDIT_WEBSITE_PAGE_DETAILS',
  EDIT_LAYOUT_DETAILS: 'EDIT_LAYOUT_DETAILS',
  EDIT_DATA_NARRATIVE: 'EDIT_DATA_NARRATIVE'
};

export default EditorNames;
