const WizardSlides = {
  CHOOSE_DATASOURCE: 0,
  CHOOSE_DATASOURCE_TYPE: 1,
  SELECT_OR_ADD_COLLECTION: 2,
  SELECT_FIELDS: 3,
  COLLECTION_GRID: 4,
  SAVE_DDL_INFO: 5
};

export default WizardSlides;
